# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/MP1BD_system_ila_0_1.xci
# IP: The module: 'MP1BD_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/bd_8e3b.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8e3b || ORIG_REF_NAME==bd_8e3b} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/bd_8e3b_ila_lib_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/bd_8e3b_ila_lib_0_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/bd_8e3b_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/MP1BD_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1BD_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/MP1BD_system_ila_0_1.xci
# IP: The module: 'MP1BD_system_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/bd_8e3b.bd
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8e3b || ORIG_REF_NAME==bd_8e3b} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/bd_8e3b_ila_lib_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila_impl.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/ila_v6_2/constraints/ila.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_8e3b_ila_lib_0 || ORIG_REF_NAME==bd_8e3b_ila_lib_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/ip/ip_0/bd_8e3b_ila_lib_0_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/bd_0/bd_8e3b_ooc.xdc

# XDC: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_system_ila_0_1/MP1BD_system_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MP1BD_system_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
