# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/zfsalti/488/MP-1/hdl/zedboard_master.xdc

# Block Designs: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/MP1BD.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD || ORIG_REF_NAME==MP1BD} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_processing_system7_0_0/MP1BD_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_processing_system7_0_0 || ORIG_REF_NAME==MP1BD_processing_system7_0_0} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_ps7_0_axi_periph_0/MP1BD_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_ps7_0_axi_periph_0 || ORIG_REF_NAME==MP1BD_ps7_0_axi_periph_0} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_rst_ps7_0_100M_0/MP1BD_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_rst_ps7_0_100M_0 || ORIG_REF_NAME==MP1BD_rst_ps7_0_100M_0} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_axi_ppm_0_1/MP1BD_axi_ppm_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_axi_ppm_0_1 || ORIG_REF_NAME==MP1BD_axi_ppm_0_1} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_xbar_0/MP1BD_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_xbar_0 || ORIG_REF_NAME==MP1BD_xbar_0} -quiet] -quiet

# IP: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_axi_gpio_0_0/MP1BD_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_axi_gpio_0_0 || ORIG_REF_NAME==MP1BD_axi_gpio_0_0} -quiet] -quiet

# IP: c:/Users/zfsalti/488/MP-1/hdl/MP1BD/ip/MP1BD_auto_pc_0/MP1BD_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MP1BD_auto_pc_0 || ORIG_REF_NAME==MP1BD_auto_pc_0} -quiet] -quiet

# XDC: C:/Users/zfsalti/488/MP-1/hdl/MP1BD/MP1BD_ooc.xdc
